### ISSUE TITLE
Add integrations example notebook

### ISSUE THREAD

**Issue by Jonathan-Adly** [tjmlabs/ColiVara-docs#4]
Using a notebook (similar to the ones in the example repo). We need examples of the following:

- Using ColiVara in langchain
- Using ColiVara in llamaindex 
- Using ColiVara using OpenRouter with any LLM

Document as needed - when complete @Mai-Khuu will turn into articles.

**Comment by Mai-Khuu** [comment]
@HalemoGPA I followed the LlamaIndex demo using the same sample files. I was able to successfully upserted all docs, and creating `gpt_4o` using `OpenAIMultiModal`

However the final `gpt_4o.complete` function call is returning an error 
`raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid value for 'content': expected a string, got null.", 'type': 'invalid_request_error', 'param': 'messages.[0].content', 'code': None}}`

**Comment by Mai-Khuu** [comment]
Updating to the latest `llama-index` package seemed to do the trick. However, I am getting another error:
```
Traceback (most recent call last):
  File "/Users/mai.khuu/my_repos/test_files/llamaindex_demo.py", line 92, in <module>
    complete_response = gpt_4o.complete(query, context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mai.khuu/.asdf/installs/python/3.12.0/lib/python3.12/site-packages/llama_index/core/instrumentation/dispatcher.py", line 321, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mai.khuu/.asdf/installs/python/3.12.0/lib/python3.12/site-packages/llama_index/core/llms/callbacks.py", line 431, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mai.khuu/.asdf/installs/python/3.12.0/lib/python3.12/site-packages/llama_index/multi_modal_llms/openai/base.py", line 344, in complete
    return self._complete(prompt, image_documents, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mai.khuu/.asdf/installs/python/3.12.0/lib/python3.12/site-packages/llama_index/core/llms/callbacks.py", line 431, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mai.khuu/.asdf/installs/python/3.12.0/lib/python3.12/site-packages/llama_index/multi_modal_llms/openai/base.py", line 217, in _complete
    message_dict = self._get_multi_modal_chat_messages(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mai.khuu/.asdf/installs/python/3.12.0/lib/python3.12/site-packages/llama_index/multi_modal_llms/openai/base.py", line 172, in _get_multi_modal_chat_messages
    generate_openai_multi_modal_chat_message(
  File "/Users/mai.khuu/.asdf/installs/python/3.12.0/lib/python3.12/site-packages/llama_index/multi_modal_llms/openai/utils.py", line 88, in generate_openai_multi_modal_chat_message
    return ChatMessage(role=role, content=completion_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mai.khuu/.asdf/installs/python/3.12.0/lib/python3.12/site-packages/llama_index/core/base/llms/types.py", line 136, in __init__
    super().__init__(**data)
  File "/Users/mai.khuu/.asdf/installs/python/3.12.0/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 4 validation errors for ChatMessage
blocks.0
  Unable to extract tag using discriminator 'block_type' [type=union_tag_not_found, input_value={'type': 'text', 'text': ...work from home policy?'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/union_tag_not_found
blocks.1
  Unable to extract tag using discriminator 'block_type' [type=union_tag_not_found, input_value={'type': 'image_url', 'im...QmCC', 'detail': 'low'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/union_tag_not_found
blocks.2
  Unable to extract tag using discriminator 'block_type' [type=union_tag_not_found, input_value={'type': 'image_url', 'im...QmCC', 'detail': 'low'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/union_tag_not_found
blocks.3
  Unable to extract tag using discriminator 'block_type' [type=union_tag_not_found, input_value={'type': 'image_url', 'im...YII=', 'detail': 'low'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/union_tag_not_found
```

**Comment by Mai-Khuu** [comment]
Another question please @HalemoGPA. Query transformations process will be different for each framework, yes? I see you include the step for query transformation for langchain but not for llama or openrouter?

**Comment by Mai-Khuu** [comment]
I have updated pydantic and the error persisted

**Comment by Mai-Khuu** [comment]
Llamaindex works now thank you @HalemoGPA 
Can confirm langchain also worked

For openrouter, although everything works, the response I received is:
```
<Response [200]>
I'm sorry, but I can't view images. If you can provide text or details from the images, I'd be happy to help answer your question about the work from home policy.
```

**Comment by Mai-Khuu** [comment]
Ah, it was a typo on my end. Got it to work now thank you for all your help :)

**Comment by Mai-Khuu** [comment]
integration example is in the docs website [here](https://app.gitbook.com/o/DHjMRQs4Vfjvi2m062WT/s/r0RGXIvkomMWAuxgus2N/guide/integrations)
